import { NewFormsObject } from "../../lib/form-field-logic/types";

export type OrgShortName = "kapiti" | "wellington";

export type Dimension = "client" | "job" | "staff";

export type OrgId = 1 | 2;

export type ExtendedDocument = Document & { appData: AppData };

export type FormDetailName = `${Dimension}Detail`;

export type FormDetails<T> = { [Key in FormDetailName]: T };

export interface AppData {
	businessName: OrgShortName;
	organisationId: OrgId;
	formOptions: NewFormsObject;
	clientDetail: ClientDetailShort[];
	jobDetail: JobDetailShort[];
}

export type ClientDetailShortKeys =
	| "accountName"
	| "billingAddressStreet"
	| "billingAddressSuburb"
	| "clientId"
	| "concat";

export type ClientDetailShort = {
	[key: string]: string | number | string[];
};

export type ClientDetailConcat =
	`Account: ${AccountName}, Billing Address: ${BillingAddressStreet}, ${BillingAddressSuburb}`;

export type ClientId = number;

export type AccountName = string;

export type BillingAddressStreet = string;

export type BillingAddressSuburb = string;

// Generated by https://quicktype.io

export type JobDetailShortKeys =
	| "clientId"
	| "jobId"
	| "accountName"
	| "dateInvoiceSent"
	| "amountInvoiced"
	| "concat";

export type JobDetailShort = {
	[key: string]: string | number | string[];
};
