import { NewFormsObject } from "../../lib/form-field-logic/types";

export type OrgShortName = "kapiti" | "wellington";

export type Dimension = "client" | "job" | "staff";

export type OrgId = 1 | 2;

export type ExtendedDocument = Document & { appData: AppData };

export interface AppData {
	businessName: OrgShortName;
	organisationId: OrgId;
	formOptions: NewFormsObject;
	clientDetail: ClientDetailShort[];
	jobDetail: JobDetailShort[];
}

export interface ClientDetailShort {
	accountName: AccountName;
	billingAddressStreet: BillingAddressStreet;
	billingAddressSuburb: BillingAddressSuburb;
	clientId: ClientId;
	concat: ClientDetailConcat;
}

export type ClientDetailConcat =
	`Account: ${AccountName}, Billing Address: ${BillingAddressStreet}, ${BillingAddressSuburb}`;

export type ClientId = number;

export type AccountName = string;

export type BillingAddressStreet = string;

export type BillingAddressSuburb = string;

// Generated by https://quicktype.io

export interface JobDetailShort {
	clientId: number;
	jobId: number;
	accountName: string;
	dateInvoiceSent: string;
	amountInvoiced: string;
	concat: string;
}
