module.exports = {
  kapiti: {
    clientDetails: {
      restfulName: "clients",
      structure: [
        {
          sectionTitle: "Identity and Contact Details",
          fields: [
            ["cd_accountName", "cd_accountType"],
            ["cd_businessName"],
            ["cd_mainContactFirstName", "cd_mainContactLastName"],
            ["cd_secondaryContactFirstName", "cd_secondaryContactLastName"],
            ["cd_mainContactLandline", "cd_mainContactMobile"],
            ["cd_mainContactEmail", "cd_clientId"],
          ],
        },
        {
          sectionTitle: "Address Details",
          fields: [
            ["cd_billingAddressStreet", "cd_billingAddressSuburb"],
            ["cd_billingAddressCity", "cd_billingAddressPostcode"],
            ["cd_territory"],
          ],
        },
        {
          sectionTitle: "Marketing Details",
          fields: [
            ["cd_customerDemographic", "cd_estimatedCustomerIncome"],
            ["cd_acquisitionChannel"],
          ],
        },
      ],
      fields: {
        cd_clientId: {
          label: "",
          fieldName: "clientId",
          fieldType: "hidden",
          readOnly: 0,
          isRequired: 0,
          additionalClasses: ["d-none"],
        },
        cd_accountType: {
          label: "Account Type",
          fieldName: "accountType",
          fieldType: "select",
          values: ["", "Individual", "Couple", "Business"],
          readOnly: 0,
          isRequired: 1,
          submitExclude: 1,
          additionalClasses: ["account-name"],
        },
        cd_accountName: {
          label: "Account Name",
          fieldName: "accountName",
          fieldType: "datalist",
          values: [""],
          readOnly: 1,
          isRequired: 1,
        },
        cd_mainContactFirstName: {
          label: "Main Contact First Name",
          fieldName: "mainContactFirstName",
          fieldType: "Text",
          readOnly: 0,
          isRequired: 1,
          additionalClasses: ["account-name"],
        },
        cd_mainContactLastName: {
          label: "Main Contact Last Name",
          fieldName: "mainContactLastName",
          fieldType: "Text",
          readOnly: 0,
          isRequired: 1,
          additionalClasses: ["account-name"],
        },
        cd_secondaryContactFirstName: {
          label: "Secondary Contact First Name",
          fieldName: "secondaryContactFirstName",
          fieldType: "Text",
          readOnly: 0,
          isRequired: 0,
          submitExclude: 0,
          additionalClasses: ["account-name"],
        },
        cd_secondaryContactLastName: {
          label: "Secondary Contact Last Name",
          fieldName: "secondaryContactLastName",
          fieldType: "Text",
          readOnly: 0,
          isRequired: 0,
          submitExclude: 0,
          additionalClasses: ["account-name"],
        },
        cd_mainContactEmail: {
          label: "Main Contact Email",
          fieldName: "mainContactEmail",
          fieldType: "Email",
          readOnly: 0,
          isRequired: 0,
        },
        cd_mainContactLandline: {
          label: "Main Contact Landline",
          fieldName: "mainContactLandline",
          fieldType: "tel",
          readOnly: 0,
          isRequired: 0,
        },
        cd_mainContactMobile: {
          label: "Main Contact Mobile",
          fieldName: "mainContactMobile",
          fieldType: "tel",
          readOnly: 0,
          isRequired: 0,
        },
        cd_businessName: {
          label: "Business Name",
          fieldName: "businessName",
          fieldType: "Text",
          readOnly: 0,
          isRequired: 0,
          additionalClasses: ["account-name"],
        },
        cd_billingAddressStreet: {
          label: "Billing Street Address",
          fieldName: "billingAddressStreet",
          fieldType: "Text",
          readOnly: 0,
          isRequired: 1,
        },
        cd_billingAddressSuburb: {
          label: "Billing Address Suburb",
          fieldName: "billingAddressSuburb",
          fieldType: "datalist",
          values: [
            "",
            "Paraparaumu",
            "Paraparaumu Beach",
            "Raumati Beach",
            "Raumati South",
            "Otaihanga",
            "Waikanae",
            "Waikanae Beach",
          ],
          readOnly: 0,
          isRequired: 1,
        },
        cd_billingAddressCity: {
          label: "",
          fieldName: "billingAddressCity",
          fieldType: "hidden",
          readOnly: 0,
          isRequired: 0,
          additionalClasses: ["d-none"],
        },
        cd_billingAddressPostcode: {
          label: "",
          fieldName: "billingAddressPostcode",
          fieldType: "hidden",
          readOnly: 0,
          isRequired: 0,
          additionalClasses: ["d-none"],
        },
        cd_territory: {
          label: "Territory",
          fieldName: "territory",
          fieldType: "select",
          values: ["", "Raumati", "Waikanae"],
          readOnly: 0,
          isRequired: 1,
        },
        cd_customerDemographic: {
          label: "Customer Demographic",
          fieldName: "customerDemographic",
          fieldType: "select",
          values: [
            "",
            "Old Retiree",
            "Active Retiree",
            "Baby Boomer (50-65 ish)",
            "Professional Couple",
            "Professional Single",
            "Young Family",
            "Property Management Company",
            "Private Landlord",
            "Other Business",
          ],
          readOnly: 0,
          isRequired: 1,
        },
        cd_estimatedCustomerIncome: {
          label: "Estimated Customer Income",
          fieldName: "estimatedCustomerIncome",
          fieldType: "select",
          values: [
            "",
            "Pension",
            "$0-$30k",
            "$30,001 - $50,000",
            "$50,001 - $70,000",
            "$70,001 - $90,000",
            "$90,001+",
          ],
          readOnly: 0,
          isRequired: 1,
        },
        cd_acquisitionChannel: {
          label: "How did they come to us?",
          fieldName: "acquisitionChannel",
          fieldType: "select",
          values: [
            "",
            "Web Enquiry Direct",
            "Google Search",
            "Call Centre",
            "Referral Business",
            "WOM Client",
            "WOM Other",
            "Vehicle Signage",
            "Print Advertising Local",
            "Facebook National",
            "Facebook Local",
            "Other Marketing Campaign (HAH National)",
            "Flyer Drop",
            "Gift Voucher",
            "Sweet Louise Voucher",
            "Other",
          ],
          readOnly: 0,
          isRequired: 1,
        },
      },
    },
    jobDetails: {
      restfulName: "jobs",
      structure: [
        {
          sectionTitle: "Account and Location Details",
          fields: [
            ["jd_accountName", "jd_billingAddress"],
            ["jd_workLocationStreetAddress", "jd_workLocationSuburb"],
            ["jd_workLocationCity", "jd_workLocationPostcode"],
          ],
        },
        {
          sectionTitle: "Job Type and Date Details",
          fields: [
            ["jd_primaryJobType", "jd_secondaryJobType"],
            ["jd_indoorsOutdoors"],
            ["jd_dateJobEnquiry", "jd_dateJobQuoted"],
            ["jd_dateWorkCommenced", "jd_dateInvoiceSent"],
          ],
        },
        {
          sectionTitle: "Job Cost Details",
          fields: [
            ["jd_amountInvoiced", "jd_costMaterials"],
            ["jd_costSubcontractor", "jd_costTipFees"],
            ["jd_costOther", "jd_jobId"],
            ["jd_hoursWorkedDave", "jd_hoursWorkedWesty"],
            ["jd_hoursWorkedPete", "jd_hoursWorkedBoof"],
            ["jd_hoursWorkedZachary", "jd_hoursWorkedMikeYeatman"],
          ],
        },
        {
          sectionTitle: "Job Feedback",
          fields: [["jd_workSatisfaction", "jd_clientId"]],
        },
      ],
      fields: {
        jd_accountName: {
          label: "Account Name",
          fieldName: "accountName",
          fieldType: "datalist",
          values: [""],
          readOnly: 0,
          isRequired: 1,
          validationDetail:
            "Give all unique existing values as options, sorted alphabetically. Do not allow new values to be entered",
        },
        jd_clientId: {
          label: "",
          fieldName: "clientId",
          fieldType: "hidden",
          readOnly: 0,
          isRequired: 0,
          additionalClasses: ["d-none"],
          validationDetail:
            "Lookup from client details sheet, column B, using accountName field to match to value in column C",
        },
        jd_billingAddress: {
          label: "Billing Address",
          fieldName: "billingAddress",
          fieldType: "textarea",
          readOnly: 1,
          isRequired: 0,
          submitExclude: 1,
          validationDetail:
            "Value from client details sheet, field billingStreetAddress (column J) to be populated as static text (this will help the user to understand whether they have selected the correct accountName value in field 1)",
        },
        jd_workLocationStreetAddress: {
          label: "Street Adress Where Work Completed",
          fieldName: "workLocationStreetAddress",
          fieldType: "text",
          readOnly: 0,
          isRequired: 1,
        },
        jd_workLocationSuburb: {
          label: "Suburb Where Work Completed",
          fieldName: "workLocationSuburb",
          fieldType: "datalist",
          values: [
            "",
            "Paraparaumu",
            "Paraparaumu Beach",
            "Raumati Beach",
            "Raumati South",
            "Otaihanga",
            "Waikanae",
            "Waikanae Beach",
          ],
          readOnly: 0,
          isRequired: 1,
        },
        jd_workLocationCity: {
          label: "City Where Work Completed",
          fieldName: "workLocationCity",
          fieldType: "hidden",
          isRequired: 0,
        },
        jd_workLocationPostcode: {
          label: "Postcode Where Work Completed",
          fieldName: "workLocationPostcode",
          fieldType: "hidden",
          isRequired: 0,
        },
        jd_primaryJobType: {
          label: "Primary Job Type",
          fieldName: "primaryJobType",
          fieldType: "select",
          values: [
            "",
            "Maintenance",
            "Painting",
            "Fencing",
            "Paving/Concrete",
            "Deck",
            "Installation",
            "Bathroom Reno",
            "Kitchen Reno",
            "Laundry Reno",
            "Sub-Contractor",
            "Rubbish Removal",
            "Furniture Removal",
            "Landscaping",
            "Carpentry",
            "Plastering Large",
            "Gib Board Replacements – large",
            "Door Installs",
            "Tiling",
            "SkyVac Gutter Clean",
            "Gutter Clean",
            "Waterblasting/Spraying",
            "Section Clean-ups",
          ],
          readOnly: 0,
          isRequired: 1,
        },
        jd_secondaryJobType: {
          label: "Seconday Job Type",
          fieldName: "secondaryJobType",
          fieldType: "select",
          values: [
            "",
            "Maintenance",
            "Painting",
            "Fencing",
            "Paving/Concrete",
            "Deck",
            "Installation",
            "Bathroom Reno",
            "Kitchen Reno",
            "Laundry Reno",
            "Sub-Contractor",
            "Rubbish Removal",
            "Furniture Removal",
            "Landscaping",
            "Carpentry",
            "Plastering Large",
            "Gib Board Replacements – large",
            "Door Installs",
            "Tiling",
            "SkyVac Gutter Clean",
            "Gutter Clean",
            "Waterblasting/Spraying",
            "Section Clean-ups",
          ],
          readOnly: 0,
          isRequired: 0,
        },
        jd_indoorsOutdoors: {
          label: "Indoors or Outdoors",
          fieldName: "indoorsOutdoors",
          fieldType: "select",
          values: ["", "Indoors", "Outdoors"],
          readOnly: 0,
          isRequired: 1,
        },
        jd_dateJobEnquiry: {
          label: "Date of Job Enquiry",
          fieldName: "dateJobEnquiry",
          fieldType: "date",
          readOnly: 0,
          isRequired: 0,
        },
        jd_dateJobQuoted: {
          label: "Date Job Quoted",
          fieldName: "dateJobQuoted",
          fieldType: "date",
          readOnly: 0,
          isRequired: 0,
        },
        jd_dateWorkCommenced: {
          label: "Date Work Commenced",
          fieldName: "dateWorkCommenced",
          fieldType: "date",
          readOnly: 0,
          isRequired: 0,
        },
        jd_dateInvoiceSent: {
          label: "Date Invoice Sent",
          fieldName: "dateInvoiceSent",
          fieldType: "date",
          readOnly: 0,
          isRequired: 1,
        },
        jd_amountInvoiced: {
          label: "Amount Invoiced (excl. GST)",
          fieldName: "amountInvoiced",
          fieldType: "number",
          readOnly: 0,
          isRequired: 1,
        },
        jd_costMaterials: {
          label: "Materials Cost",
          fieldName: "costMaterials",
          fieldType: "number",
          readOnly: 0,
          isRequired: 0,
        },
        jd_costTipFees: {
          label: "Tip Fees",
          fieldName: "costTipFees",
          fieldType: "number",
          readOnly: 0,
          isRequired: 0,
        },
        jd_costSubcontractor: {
          label: "Sub-Contractor Cost",
          fieldName: "costSubcontractor",
          fieldType: "number",
          readOnly: 0,
          isRequired: 0,
        },
        jd_costOther: {
          label: "Other Cost (Excluding Staff Cost)",
          fieldName: "costOther",
          fieldType: "number",
          readOnly: 0,
          isRequired: 0,
        },
        jd_jobId: {
          label: "",
          fieldName: "jobId",
          fieldType: "hidden",
          readOnly: 0,
          isRequired: 0,
          additionalClasses: ["d-none"],
        },
        jd_hoursWorkedDave: {
          label: "Dave Hours Worked",
          fieldName: "hoursWorkedDave",
          fieldType: "number",
          readOnly: 0,
          isRequired: 0,
          additionalClasses: ["staff-hours"],
          validationDetail: "Must have > 0 hours across all staff",
        },
        jd_hoursWorkedWesty: {
          label: "Westy Hours Worked",
          fieldName: "hoursWorkedWesty",
          fieldType: "number",
          readOnly: 0,
          isRequired: 0,
          additionalClasses: ["staff-hours"],
          validationDetail: "Must have > 0 hours across all staff",
        },
        jd_hoursWorkedPete: {
          label: "Pete Hours Worked",
          fieldName: "hoursWorkedPete",
          fieldType: "number",
          readOnly: 0,
          isRequired: 0,
          additionalClasses: ["staff-hours"],
          validationDetail: "Must have > 0 hours across all staff",
        },
        jd_hoursWorkedBoof: {
          label: "Boof Hours Worked",
          fieldName: "hoursWorkedBoof",
          fieldType: "number",
          readOnly: 0,
          isRequired: 0,
          additionalClasses: ["staff-hours"],
          validationDetail: "Must have > 0 hours across all staff",
        },
        jd_hoursWorkedZachary: {
          label: "Zachary Hours Worked",
          fieldName: "hoursWorkedZachary",
          fieldType: "number",
          readOnly: 0,
          isRequired: 0,
          additionalClasses: ["staff-hours"],
          validationDetail: "Must have > 0 hours across all staff",
        },
        jd_hoursWorkedMikeYeatman: {
          label: "Mike Yeatman Hours Worked",
          fieldName: "hoursWorkedMikeYeatman",
          fieldType: "number",
          readOnly: 0,
          isRequired: 0,
          additionalClasses: ["staff-hours"],
          validationDetail: "Must have > 0 hours across all staff",
        },
        jd_workSatisfaction: {
          label: "Satisfaction With Work?",
          fieldName: "workSatisfaction",
          fieldType: "select",
          values: ["", 5, 4, 3, 2, 1],
          readOnly: 0,
          isRequired: 1,
        },
      },
    },
  },
  wellington: {
    clientDetails: {
      restfulName: "clients",
      structure: [
        {
          sectionTitle: "Identity and Contact Details",
          fields: [
            ["cd_accountName", "cd_accountType"],
            ["cd_businessName"],
            ["cd_mainContactFirstName", "cd_mainContactLastName"],
            ["cd_secondaryContactFirstName", "cd_secondaryContactLastName"],
            ["cd_mainContactLandline", "cd_mainContactMobile"],
            ["cd_mainContactEmail", "cd_clientId"],
          ],
        },
        {
          sectionTitle: "Address Details",
          fields: [
            ["cd_billingAddressStreet", "cd_billingAddressSuburb"],
            ["cd_billingAddressCity", "cd_billingAddressPostcode"],
            ["cd_territory"],
          ],
        },
        {
          sectionTitle: "Marketing Details",
          fields: [
            ["cd_customerDemographic", "cd_estimatedCustomerIncome"],
            ["cd_acquisitionChannel"],
          ],
        },
      ],
      fields: {
        cd_clientId: {
          label: "",
          fieldName: "clientId",
          fieldType: "hidden",
          readOnly: 0,
          isRequired: 0,
          additionalClasses: ["d-none"],
        },
        cd_accountType: {
          label: "Account Type",
          fieldName: "accountType",
          fieldType: "select",
          values: ["", "Individual", "Couple", "Business"],
          readOnly: 0,
          isRequired: 1,
          submitExclude: 1,
          additionalClasses: ["account-name"],
        },
        cd_accountName: {
          label: "Account Name",
          fieldName: "accountName",
          fieldType: "datalist",
          values: [""],
          readOnly: 1,
          isRequired: 1,
        },
        cd_mainContactFirstName: {
          label: "Main Contact First Name",
          fieldName: "mainContactFirstName",
          fieldType: "Text",
          readOnly: 0,
          isRequired: 1,
          additionalClasses: ["account-name"],
        },
        cd_mainContactLastName: {
          label: "Main Contact Last Name",
          fieldName: "mainContactLastName",
          fieldType: "Text",
          readOnly: 0,
          isRequired: 1,
          additionalClasses: ["account-name"],
        },
        cd_secondaryContactFirstName: {
          label: "Secondary Contact First Name",
          fieldName: "secondaryContactFirstName",
          fieldType: "Text",
          readOnly: 0,
          isRequired: 0,
          submitExclude: 0,
          additionalClasses: ["account-name"],
        },
        cd_secondaryContactLastName: {
          label: "Secondary Contact Last Name",
          fieldName: "secondaryContactLastName",
          fieldType: "Text",
          readOnly: 0,
          isRequired: 0,
          submitExclude: 0,
          additionalClasses: ["account-name"],
        },
        cd_mainContactEmail: {
          label: "Main Contact Email",
          fieldName: "mainContactEmail",
          fieldType: "Email",
          readOnly: 0,
          isRequired: 0,
        },
        cd_mainContactLandline: {
          label: "Main Contact Landline",
          fieldName: "mainContactLandline",
          fieldType: "tel",
          readOnly: 0,
          isRequired: 0,
        },
        cd_mainContactMobile: {
          label: "Main Contact Mobile",
          fieldName: "mainContactMobile",
          fieldType: "tel",
          readOnly: 0,
          isRequired: 0,
        },
        cd_businessName: {
          label: "Business Name",
          fieldName: "businessName",
          fieldType: "Text",
          readOnly: 0,
          isRequired: 0,
          additionalClasses: ["account-name"],
        },
        cd_billingAddressStreet: {
          label: "Billing Street Address",
          fieldName: "billingAddressStreet",
          fieldType: "Text",
          readOnly: 0,
          isRequired: 1,
        },
        cd_billingAddressSuburb: {
          label: "Billing Address Suburb",
          fieldName: "billingAddressSuburb",
          fieldType: "datalist",
          values: [
            "",
            "Pukerua Bay",
            "Plimmerton",
            "Whitby",
            "Porirua",
            "Porirua East",
            "Tawa",
            "Johnsonville",
            "Churton Park",
            "Newlands ",
            "Khandallah",
            "Wellington CBD",
            "Te Aro",
            "Newtown",
            "Miramar",
            "Kilbirnie",
            "Mount Victoria",
            "Brooklyn",
            "Karori",
            "Wilton",
          ],
          readOnly: 0,
          isRequired: 1,
        },
        cd_billingAddressCity: {
          label: "",
          fieldName: "billingAddressCity",
          fieldType: "hidden",
          readOnly: 0,
          isRequired: 0,
          additionalClasses: "[d-none]",
        },
        cd_billingAddressPostcode: {
          label: "",
          fieldName: "billingAddressPostcode",
          fieldType: "hidden",
          readOnly: 0,
          isRequired: 0,
          additionalClasses: "[d-none]",
        },
        cd_territory: {
          label: "Territory",
          fieldName: "territory",
          fieldType: "select",
          values: [""],
          readOnly: 0,
          isRequired: 1,
        },
        cd_customerDemographic: {
          label: "Customer Demographic",
          fieldName: "customerDemographic",
          fieldType: "select",
          values: [
            "",
            "Old Retiree",
            "Active Retiree",
            "Baby Boomer (50-65 ish)",
            "Professional Couple",
            "Professional Single",
            "Young Family",
            "Property Management Company",
            "Private Landlord",
            "Other Business",
          ],
          readOnly: 0,
          isRequired: 1,
        },
        cd_estimatedCustomerIncome: {
          label: "Estimated Customer Income",
          fieldName: "estimatedCustomerIncome",
          fieldType: "select",
          values: [
            "",
            "Pension",
            "$0-$30k",
            "$30,001 - $50,000",
            "$50,001 - $70,000",
            "$70,001 - $90,000",
            "$90,001+",
          ],
          readOnly: 0,
          isRequired: 1,
        },
        cd_acquisitionChannel: {
          label: "How did they come to us?",
          fieldName: "acquisitionChannel",
          fieldType: "select",
          values: [
            "",
            "Web Enquiry Direct",
            "Google Search",
            "Call Centre",
            "Referral Business",
            "WOM Client",
            "WOM Other",
            "Vehicle Signage",
            "Print Advertising Local",
            "Facebook National",
            "Facebook Local",
            "Other Marketing Campaign (HAH National)",
            "Flyer Drop",
            "Gift Voucher",
            "Sweet Louise Voucher",
            "Other",
          ],
          readOnly: 0,
          isRequired: 1,
        },
      },
    },
    jobDetails: {
      restfulName: "jobs",
      structure: [
        {
          sectionTitle: "Account and Location Details",
          fields: [
            ["jd_accountName", "jd_billingAddress"],
            ["jd_workLocationStreetAddress", "jd_workLocationSuburb"],
            ["jd_workLocationCity", "jd_workLocationPostcode"],
          ],
        },
        {
          sectionTitle: "Job Type and Date Details",
          fields: [
            ["jd_primaryJobType", "jd_secondaryJobType"],
            ["jd_indoorsOutdoors"],
            ["jd_dateJobEnquiry", "jd_dateJobQuoted"],
            ["jd_dateWorkCommenced", "jd_dateInvoiceSent"],
          ],
        },
        {
          sectionTitle: "Job Cost Details",
          fields: [
            ["jd_amountInvoiced", "jd_costMaterials"],
            ["jd_costSubcontractor", "jd_costTipFees"],
            ["jd_costOther", "jd_jobId"],
            ["jd_hoursWorkedDarryl", "jd_hoursWorkedIanMcGinty"],
            ["jd_hoursWorkedPeterPeacock", "jd_hoursWorkedTysonHill"],
            ["jd_hoursWorkedWesty", "jd_hoursWorkedTroyRosson"],
            // ["jd_hoursWorkedHubby6", "jd_hoursWorkedHubby7"],
          ],
        },
        {
          sectionTitle: "Job Feedback",
          fields: [["jd_workSatisfaction", "jd_clientId"]],
        },
      ],
      fields: {
        jd_accountName: {
          label: "Account Name",
          fieldName: "accountName",
          fieldType: "datalist",
          values: [""],
          readOnly: 0,
          isRequired: 1,
          validationDetail:
            "Give all unique existing values as options, sorted alphabetically. Do not allow new values to be entered",
        },
        jd_clientId: {
          label: "",
          fieldName: "clientId",
          fieldType: "hidden",
          readOnly: 0,
          isRequired: 0,
          additionalClasses: ["d-none"],
          validationDetail:
            "Lookup from client details sheet, column B, using accountName field to match to value in column C",
        },
        jd_billingAddress: {
          label: "Billing Address",
          fieldName: "billingAddress",
          fieldType: "textarea",
          readOnly: 1,
          isRequired: 0,
          submitExclude: 1,
          validationDetail:
            "Value from client details sheet, field billingStreetAddress (column J) to be populated as static text (this will help the user to understand whether they have selected the correct accountName value in field 1)",
        },
        jd_workLocationStreetAddress: {
          label: "Street Adress Where Work Completed",
          fieldName: "workLocationStreetAddress",
          fieldType: "text",
          readOnly: 0,
          isRequired: 1,
        },
        jd_workLocationSuburb: {
          label: "Suburb Where Work Completed",
          fieldName: "workLocationSuburb",
          fieldType: "datalist",
          values: [
            "",
            "Pukerua Bay",
            "Plimmerton",
            "Whitby",
            "Porirua",
            "Porirua East",
            "Tawa",
            "Johnsonville",
            "Churton Park",
            "Newlands ",
            "Khandallah",
            "Wellington CBD",
            "Te Aro",
            "Newtown",
            "Miramar",
            "Kilbirnie",
            "Mount Victoria",
            "Brooklyn",
            "Karori",
            "Wilton",
          ],
          readOnly: 0,
          isRequired: 1,
        },
        jd_workLocationCity: {
          label: "City Where Work Completed",
          fieldName: "workLocationCity",
          fieldType: "hidden",
          isRequired: 1,
        },
        jd_workLocationPostcode: {
          label: "Postcode Where Work Completed",
          fieldName: "workLocationPostcode",
          fieldType: "hidden",
          isRequired: 1,
        },
        jd_primaryJobType: {
          label: "Primary Job Type",
          fieldName: "primaryJobType",
          fieldType: "select",
          values: [
            "",
            "Maintenance",
            "Painting",
            "Fencing",
            "Paving/Concrete",
            "Deck",
            "Installation",
            "Bathroom Reno",
            "Kitchen Reno",
            "Laundry Reno",
            "Sub-Contractor",
            "Rubbish Removal",
            "Furniture Removal",
            "Landscaping",
            "Carpentry",
            "Plastering Large",
            "Gib Board Replacements – large",
            "Door Installs",
            "Tiling",
            "SkyVac Gutter Clean",
            "Gutter Clean",
            "Waterblasting/Spraying",
            "Section Clean-ups",
          ],
          readOnly: 0,
          isRequired: 1,
        },
        jd_secondaryJobType: {
          label: "Seconday Job Type",
          fieldName: "secondaryJobType",
          fieldType: "select",
          values: [
            "",
            "Maintenance",
            "Painting",
            "Fencing",
            "Paving/Concrete",
            "Deck",
            "Installation",
            "Bathroom Reno",
            "Kitchen Reno",
            "Laundry Reno",
            "Sub-Contractor",
            "Rubbish Removal",
            "Furniture Removal",
            "Landscaping",
            "Carpentry",
            "Plastering Large",
            "Gib Board Replacements – large",
            "Door Installs",
            "Tiling",
            "SkyVac Gutter Clean",
            "Gutter Clean",
            "Waterblasting/Spraying",
            "Section Clean-ups",
          ],
          readOnly: 0,
          isRequired: 0,
        },
        jd_indoorsOutdoors: {
          label: "Indoors or Outdoors",
          fieldName: "indoorsOutdoors",
          fieldType: "select",
          values: ["", "Indoors", "Outdoors"],
          readOnly: 0,
          isRequired: 1,
        },
        jd_dateJobEnquiry: {
          label: "Date of Job Enquiry",
          fieldName: "dateJobEnquiry",
          fieldType: "date",
          readOnly: 0,
          isRequired: 0,
        },
        jd_dateJobQuoted: {
          label: "Date Job Quoted",
          fieldName: "dateJobQuoted",
          fieldType: "date",
          readOnly: 0,
          isRequired: 0,
        },
        jd_dateWorkCommenced: {
          label: "Date Work Commenced",
          fieldName: "dateWorkCommenced",
          fieldType: "date",
          readOnly: 0,
          isRequired: 0,
        },
        jd_dateInvoiceSent: {
          label: "Date Invoice Sent",
          fieldName: "dateInvoiceSent",
          fieldType: "date",
          readOnly: 0,
          isRequired: 1,
        },
        jd_amountInvoiced: {
          label: "Amount Invoiced (excl. GST)",
          fieldName: "amountInvoiced",
          fieldType: "number",
          readOnly: 0,
          isRequired: 1,
        },
        jd_costMaterials: {
          label: "Materials Cost",
          fieldName: "costMaterials",
          fieldType: "number",
          readOnly: 0,
          isRequired: 0,
        },
        jd_costTipFees: {
          label: "Tip Fees",
          fieldName: "costTipFees",
          fieldType: "number",
          readOnly: 0,
          isRequired: 0,
        },
        jd_costSubcontractor: {
          label: "Sub-Contractor Cost",
          fieldName: "costSubcontractor",
          fieldType: "number",
          readOnly: 0,
          isRequired: 0,
        },
        jd_costOther: {
          label: "Other Cost (Excluding Staff Cost)",
          fieldName: "costOther",
          fieldType: "number",
          readOnly: 0,
          isRequired: 0,
        },
        jd_jobId: {
          label: "",
          fieldName: "jobId",
          fieldType: "hidden",
          readOnly: 0,
          isRequired: 0,
          additionalClasses: ["d-none"],
        },
        jd_hoursWorkedDarryl: {
          label: "Darryl Hours",
          fieldName: "hoursWorkedDarryl",
          fieldType: "number",
          readOnly: 0,
          isRequired: 0,
          additionalClasses: ["staff-hours"],
          validationDetail: "Must have > 0 hours across all staff",
        },
        jd_hoursWorkedWayne: {
          label: "Wayne Hours",
          fieldName: "hoursWorkedWayne",
          fieldType: "number",
          readOnly: 0,
          isRequired: 0,
          additionalClasses: ["staff-hours"],
          validationDetail: "Must have > 0 hours across all staff",
        },
        jd_hoursWorkedWarrick: {
          label: "Warrick Hours",
          fieldName: "hoursWorkedWarrick",
          fieldType: "number",
          readOnly: 0,
          isRequired: 0,
          additionalClasses: ["staff-hours"],
          validationDetail: "Must have > 0 hours across all staff",
        },
        jd_hoursWorkedIanMcGinty: {
          label: "Ian McGinty Hours",
          fieldName: "hoursWorkedIanMcGinty",
          fieldType: "number",
          readOnly: 0,
          isRequired: 0,
          additionalClasses: ["staff-hours"],
          validationDetail: "Must have > 0 hours across all staff",
        },
        jd_hoursWorkedTysonHill: {
          label: "Tyson Hill Hours",
          fieldName: "hoursWorkedTysonHill",
          fieldType: "number",
          readOnly: 0,
          isRequired: 0,
          additionalClasses: ["staff-hours"],
          validationDetail: "Must have > 0 hours across all staff",
        },
        jd_hoursWorkedTroyRosson: {
          label: "Troy Rosson Hours",
          fieldName: "hoursWorkedTroyRosson",
          fieldType: "number",
          readOnly: 0,
          isRequired: 0,
          additionalClasses: ["staff-hours"],
          validationDetail: "Must have > 0 hours across all staff",
        },
        jd_hoursWorkedWesty: {
          label: "Westy Hours",
          fieldName: "hoursWorkedWesty",
          fieldType: "number",
          readOnly: 0,
          isRequired: 0,
          additionalClasses: ["staff-hours"],
          validationDetail: "Must have > 0 hours across all staff",
        },
        jd_hoursWorkedHubby6: {
          label: "Hubby 6 Hours",
          fieldName: "hoursWorkedHubby6",
          fieldType: "number",
          readOnly: 0,
          isRequired: 0,
          additionalClasses: ["staff-hours"],
          validationDetail: "Must have > 0 hours across all staff",
        },
        jd_hoursWorkedHubby7: {
          label: "Hubby 7 Hours",
          fieldName: "hoursWorkedHubby7",
          fieldType: "number",
          readOnly: 0,
          isRequired: 0,
          additionalClasses: ["staff-hours"],
          validationDetail: "Must have > 0 hours across all staff",
        },
        jd_hoursWorkedPeterPeacock: {
          label: "Peter Peacock Hours",
          fieldName: "hoursWorkedPeterPeacock",
          fieldType: "number",
          readOnly: 0,
          isRequired: 0,
          additionalClasses: ["staff-hours"],
          validationDetail: "Must have > 0 hours across all staff",
        },
        jd_workSatisfaction: {
          label: "Satisfaction With Work?",
          fieldName: "workSatisfaction",
          fieldType: "select",
          values: ["", 5, 4, 3, 2, 1],
          readOnly: 0,
          isRequired: 1,
        },
      },
    },
  },
};
